From ubuntu:latest

RUN apt-get update
RUN apt-get install -y \
      python3  python3-pandas\
      python3-numpy python3-scipy  
       
      


COPY my_csv_reader_new.py .
volume ["c/users/hamid.t/class4-notebook"]
CMD ["python3","-u","my_csv_reader_new.py","breast_cancer.csv"]




